### ISSUE TITLE
Select PHP framework to use

### ISSUE THREAD

**Issue by lcabrini** [LinuxAccra-UserGroup/la-webapp#5]
It is time to select the PHP framework to use. This issue is part of the 'Setup' milestone, so closing it works towards that milestone.

I suggest we don't linger too long on this issue.

**Comment by lcabrini** [comment]
I will suggest [Symfony](http://symfony.com) simply because that is the PHP framework I'm most familiar with. But if I were pressed to justify my choice I would say this.
1. It comes with a lot of functionality, being a full-stack framework
2. It is highly modular
3. It's building blocks, Symfony components are quite considered to be of good quality in the PHP world and quite a few of them are used by projects like Laravel and Drupal 8.
4. It's templating engine, Twig, is very similar in many ways to the Django templating engine
5. It's got a built-in webserver for development purposes. No need to copy files into a web directory just to test
6. Good debugging support

Of course, there are some doubts to be raised as well:
1. Being a full-stack framework, it can be fairly complex
2. Do we even need a full-stack framework for what we are doing?
3. We could still use some Symfony components without having to use the whole framework. I have used  both Twig (templating) and Doctrine (SQL/ORM) outside of the framework itself.

So let's hear other alternatives. Maybe somebody could suggest something really light. Something like Python's flask. I really don't mind learning something new.

**Comment by elvisron** [comment]
This is really helping me design the wireframe. I wish I could get more from members so we can come out with an excellent user experience.

**Comment by elvisron** [comment]
I have reviewed most frameworks and I have come to the conclusion that we could use any of the top 10 which, of course, Symfony is a part. Since you are familiar with it I don't think another option would help.

**Comment by laudb** [comment]
Yeah, let's go with Symfony, I'll love to try my hands on php and this framework. @lcabrini since you're most familiar with it, we could start there. I've also heard a lot about Slim php, Python's flask is also another light option as opposed to django.

**Comment by lcabrini** [comment]
@laudb: I love flask. I'd be very happy to use it. The _only_ benefit of PHP, in my opinion, is that most web hosts support it well. With python, it is more dicey. I've hosted some python stuff on Dreamhost, and it goes through passenger (which was originally for Ruby apps) and it crashes every so often. I don't know if they now offer mod_wsgi (much more stable IMO). 

The other issue is that we should select a language that allows as many people as possible to contribute. I really favor python over PHP, but what do the others say? And as I said, I'm used to learning new things, so there is no need to select a framework that I know. I'll learn whichever framework we decide on.

If we still want to stick with Symfony, I'll set up an issue for it and do the basic setup. Maybe this will be a good idea because we could discuss for weeks and weeks about which framework to use. Let's just decide for one and use it.

**Comment by lcabrini** [comment]
No update here. Have we decided for Symfony? If so I can push my repo.

**Comment by elvisron** [comment]
Yes. Let's go with that.
